/**
 * BIM OOTB — RouteWalker JS (ported from RouteWalker.java)
 * Copyright (c) 2025-2026 Redhuan D. Oon <red1org@gmail.com>
 * SPDX-License-Identifier: MIT
 *
 * Port of DAGCompiler/src/main/java/com/bim/compiler/mep/RouteWalker.java
 * Reads MEP recipes from mep_rw.db (sidecar, cached via IndexedDB).
 * Writes RW2D-prefixed elements into the building's extracted DB.
 *
 * Data chain:
 *   mep_rw.db: ad_space_type → ad_space_type_mep_bom → ad_placement_offset → _shim_attributes
 *   mep_rw.db: ad_mep_pattern (CW/SP topology) + ad_mep_anchor (known buildings)
 *   building DB: elements_meta + element_transforms (read ARC envelope, write MEP)
 *
 * Session isolation: this file is NEW. Does not edit any existing file.
 * GUID prefix: RW2D- (never collides with IFC-extracted or Java RW- elements)
 */

// ─── Constants ───────────────────────────────────────────────
var RW_PREFIX = 'RW2D-';
var MEP_RW_DB_URL = 'mep_rw.db';  // relative to viewer, or full OCI URL
var RW_PIPE_NOMINAL_MM = 50;
var RW_PIPE_CROSS = RW_PIPE_NOMINAL_MM * 1.5;  // bbox cross-section
var RW_MAX_PAIR_DIST = 50.0;  // metres — skip pairs > 50m apart
var RW_ARC_CLASH_TOL = -0.01; // metres — pipes may touch walls but not penetrate

// ─── MEP product → IFC class mapping ────────────────────────
var RW_IFC_MAP = {
  TOILET:         { cls: 'IfcFlowTerminal',    disc: 'PLB', rgba: '0,119,190,255' },
  SINK:           { cls: 'IfcFlowTerminal',    disc: 'PLB', rgba: '0,119,190,255' },
  FLOOR_TRAP:     { cls: 'IfcFlowTerminal',    disc: 'PLB', rgba: '0,119,190,255' },
  WASHING_MACHINE_TAP: { cls: 'IfcFlowTerminal', disc: 'PLB', rgba: '0,119,190,255' },
  OUTLET:         { cls: 'IfcOutlet',          disc: 'ELEC', rgba: '255,200,0,255' },
  OUTLET_GFCI:    { cls: 'IfcOutlet',          disc: 'ELEC', rgba: '255,200,0,255' },
  LIGHT:          { cls: 'IfcLightFixture',    disc: 'ELEC', rgba: '255,220,100,255' },
  SWITCH:         { cls: 'IfcSwitchingDevice', disc: 'ELEC', rgba: '255,200,0,255' },
  EXHAUST_FAN:    { cls: 'IfcFan',             disc: 'ACMV', rgba: '100,200,255,255' },
  SPRINKLER:      { cls: 'IfcFlowTerminal',    disc: 'FP',   rgba: '255,80,80,255' },
  AIRCON_POINT:   { cls: 'IfcUnitaryEquipment',disc: 'ACMV', rgba: '100,200,255,255' },
  DATA_POINT:     { cls: 'IfcCommunicationsAppliance', disc: 'ELEC', rgba: '180,180,255,255' },
  // Pipe segments generated by walker
  PIPE_CW:        { cls: 'IfcPipeSegment',     disc: 'PLB', rgba: '0,119,190,255' },
  PIPE_SP:        { cls: 'IfcPipeSegment',     disc: 'PLB', rgba: '139,90,43,255' },
  // Defaults
  _DEFAULT:       { cls: 'IfcBuildingElementProxy', disc: 'MEP', rgba: '180,180,180,255' }
};

// ─── Module state ────────────────────────────────────────────
var _rwDb = null;      // sql.js instance for mep_rw.db
var _rwReady = false;
var _rwGuidCounter = 0;

// ═══════════════════════════════════════════════════════════════
// PUBLIC API
// ═══════════════════════════════════════════════════════════════

/**
 * Initialise RouteWalker: fetch mep_rw.db, open as sql.js instance.
 * Call once at page load. Caches in IndexedDB (same pattern as building DB).
 * @param {object} SQL - initSqlJs result (sql.js factory)
 * @param {string} [baseUrl] - base URL for mep_rw.db (default: relative)
 * @returns {Promise<boolean>} true if ready
 */
async function rwInit(SQL, baseUrl) {
  if (_rwReady) return true;
  var url = (baseUrl || '') + MEP_RW_DB_URL;
  try {
    var buf = await _rwFetchCached(url);
    _rwDb = new SQL.Database(new Uint8Array(buf));
    _rwReady = true;
    var counts = _rwDb.exec(
      "SELECT (SELECT COUNT(*) FROM ad_space_type_mep_bom) as bom, " +
      "(SELECT COUNT(*) FROM ad_mep_pattern) as pat, " +
      "(SELECT COUNT(*) FROM ad_mep_anchor) as anc, " +
      "(SELECT COUNT(*) FROM ad_placement_offset) as off, " +
      "(SELECT COUNT(*) FROM _shim_attributes) as shim"
    );
    var r = counts[0].values[0];
    console.log('§RW_INIT mep_rw.db loaded bom=' + r[0] + ' patterns=' + r[1] +
                ' anchors=' + r[2] + ' offsets=' + r[3] + ' shims=' + r[4]);
    return true;
  } catch (e) {
    console.warn('§RW_INIT_FAIL ' + e.message);
    return false;
  }
}

/**
 * Run RouteWalker on a building DB.
 * Path A: building has anchors in mep_rw.db → use Java-style pattern walk
 * Path B: building has no anchors → generate from room BOM recipes + placement offsets
 *
 * @param {object} buildingDb - sql.js Database instance (building's extracted DB)
 * @param {string} buildingName - building name (matches source_building in anchors)
 * @param {object} [opts] - { rooms: [{id,type,storey,bbox}], forceRegen: false }
 * @returns {object} { fixtures, pipes, clashSkipped, total }
 */
function rwWalk(buildingDb, buildingName, opts) {
  if (!_rwReady) { console.warn('§RW_WALK_FAIL not initialised'); return null; }
  opts = opts || {};
  _rwGuidCounter = 0;

  // Resolve actual building name from DB (may differ from ERP anchor key)
  var dbBldName = buildingName;
  try {
    var bldRow = buildingDb.exec("SELECT DISTINCT building FROM elements_meta LIMIT 1");
    if (bldRow.length && bldRow[0].values.length) dbBldName = bldRow[0].values[0][0];
  } catch (e) { /* use passed name */ }

  // Clean previous RW2D- elements (idempotent re-run)
  try {
    buildingDb.run("DELETE FROM elements_meta WHERE guid LIKE 'RW2D-%'");
    buildingDb.run("DELETE FROM element_transforms WHERE guid LIKE 'RW2D-%'");
  } catch (e) { /* tables may not exist yet */ }

  // Load ARC envelope from building DB for clash checking
  var arcEnvelope = _rwLoadArcEnvelope(buildingDb);

  // Check if this building has pre-mined anchors (try exact name, then fuzzy)
  var anchorKey = _rwFindAnchorKey(buildingName, dbBldName);
  var hasAnchors = anchorKey !== null;

  var result = { fixtures: 0, pipes: 0, clashSkipped: 0, total: 0 };

  if (hasAnchors && !opts.forceRegen) {
    // Path A: pattern walk using pre-mined anchors (Java port)
    console.log('§RW_PATH_A building=' + buildingName + ' anchorKey=' + anchorKey);
    var patResult = _rwPatternWalk(buildingDb, anchorKey, arcEnvelope);
    result.pipes = patResult.cwLines + patResult.spLines;
    result.clashSkipped = patResult.clashSkipped;
  }

  // Path B: room-based BOM placement (always runs — adds fixtures)
  // Uses dbBldName for DB queries (the actual building column value)
  var rooms = opts.rooms || _rwDetectRooms(buildingDb, dbBldName);
  if (rooms.length > 0) {
    console.log('§RW_PATH_B building=' + dbBldName + ' rooms=' + rooms.length);
    var bomResult = _rwPlaceFromBOM(buildingDb, dbBldName, rooms, arcEnvelope);
    result.fixtures += bomResult.placed;

    // If no pre-mined anchors, also generate pipe runs from placed fixtures
    if (!hasAnchors || opts.forceRegen) {
      var pipeResult = _rwConnectFixtures(buildingDb, dbBldName, arcEnvelope);
      result.pipes += pipeResult.pipes;
      result.clashSkipped += pipeResult.clashSkipped;
    }
  }

  result.total = result.fixtures + result.pipes;
  console.log('§RW_WALK building=' + buildingName + ' fixtures=' + result.fixtures +
              ' pipes=' + result.pipes + ' clashSkipped=' + result.clashSkipped +
              ' total=' + result.total);
  return result;
}


/**
 * Find anchor key in mep_rw.db for this building.
 * Tries exact match, then fuzzy (DB name contains anchor key or vice versa).
 * e.g. DB has 'Ifc2x3_Duplex_Architecture', anchors keyed as 'Duplex' → match.
 */
function _rwFindAnchorKey(buildingName, dbBldName) {
  // Get all source_building values from anchors
  var rows = _rwDb.exec("SELECT DISTINCT source_building FROM ad_mep_anchor");
  if (!rows.length) return null;
  var keys = rows[0].values.map(function(v) { return v[0]; });

  // Exact match
  if (keys.indexOf(buildingName) >= 0) return buildingName;
  if (keys.indexOf(dbBldName) >= 0) return dbBldName;

  // Fuzzy: anchor key is substring of DB name or vice versa
  var candidates = [buildingName, dbBldName];
  for (var c = 0; c < candidates.length; c++) {
    var name = candidates[c].toUpperCase();
    for (var i = 0; i < keys.length; i++) {
      var key = keys[i].toUpperCase();
      if (name.indexOf(key) >= 0 || key.indexOf(name) >= 0) {
        console.log('§RW_ANCHOR_MATCH fuzzy "' + candidates[c] + '" → "' + keys[i] + '"');
        return keys[i];
      }
    }
  }
  return null;
}

// ═══════════════════════════════════════════════════════════════
// PATH A: Pattern walk (Java RouteWalker port)
// ═══════════════════════════════════════════════════════════════

function _rwPatternWalk(buildingDb, buildingName, arcEnvelope) {
  var cwSteps = _rwLoadPatternSteps('CW', buildingName);
  var spSteps = _rwLoadPatternSteps('SP', buildingName);
  var allAnchors = _rwLoadAnchors(buildingName);

  if (!allAnchors.length) {
    console.warn('§RW_WARN no anchors for ' + buildingName);
    return { cwLines: 0, spLines: 0, clashSkipped: 0 };
  }

  var cwResult = cwSteps.length ? _rwApplyPattern(buildingDb, 'CW', cwSteps, allAnchors, arcEnvelope, buildingName) : { emitted: 0, clashSkipped: 0 };
  var spResult = spSteps.length ? _rwApplyPattern(buildingDb, 'SP', spSteps, allAnchors, arcEnvelope, buildingName) : { emitted: 0, clashSkipped: 0 };

  console.log('§RW_PATTERN ' + buildingName + ': CW=' + cwResult.emitted +
              ' SP=' + spResult.emitted + ' clashSkipped=' + (cwResult.clashSkipped + spResult.clashSkipped));
  return {
    cwLines: cwResult.emitted,
    spLines: spResult.emitted,
    clashSkipped: cwResult.clashSkipped + spResult.clashSkipped
  };
}

// A1. Load pattern steps from mep_rw.db
function _rwLoadPatternSteps(discipline, buildingType) {
  var rows = _rwDb.exec(
    "SELECT pattern_id, discipline, building_type, sequence, from_node_type, to_node_type, " +
    "direction_axis, piece_type, offset_rule, COALESCE(gradient, 0) " +
    "FROM ad_mep_pattern WHERE discipline = '" + discipline + "' " +
    "ORDER BY CASE WHEN building_type = '" + buildingType.replace(/'/g, "''") + "' THEN 0 ELSE 1 END, sequence"
  );
  if (!rows.length || !rows[0].values.length) return [];
  var selectedId = rows[0].values[0][0];
  var steps = [];
  for (var i = 0; i < rows[0].values.length; i++) {
    var v = rows[0].values[i];
    if (v[0] !== selectedId) break; // only first (best) pattern
    steps.push({
      patternId: v[0], discipline: v[1], buildingType: v[2], sequence: v[3],
      fromNodeType: v[4], toNodeType: v[5], directionAxis: v[6],
      pieceType: v[7], offsetRule: v[8], gradient: v[9]
    });
  }
  if (steps.length) console.log('§RW_PATTERN_LOADED ' + discipline + ' pattern=' + selectedId + ' steps=' + steps.length);
  return steps;
}

// A2. Load anchors from mep_rw.db
function _rwLoadAnchors(buildingName) {
  var rows = _rwDb.exec(
    "SELECT anchor_id, anchor_type, x_m, y_m, z_m, storey " +
    "FROM ad_mep_anchor WHERE source_building = '" + buildingName.replace(/'/g, "''") + "'"
  );
  if (!rows.length) return [];
  return rows[0].values.map(function(v) {
    return { anchorId: v[0], anchorType: v[1], x: v[2], y: v[3], z: v[4], storey: v[5] || 'Unknown' };
  });
}

// Node type mapping (same logic as Java)
function _rwToNodeType(anchorType, discipline) {
  if (anchorType === 'METER') return discipline === 'SP' ? 'STACK' : 'METER';
  if (anchorType === 'FIXTURE') return 'FIXTURE';
  if (anchorType === 'VALVE') return 'VALVE';
  return 'JUNCTION';
}

// A3. Apply pattern — pair anchors, check clash, emit pipe segments
function _rwApplyPattern(buildingDb, discipline, steps, allAnchors, arcEnvelope, buildingName) {
  // Group anchors by storey
  var byStorey = {};
  allAnchors.forEach(function(a) {
    var s = a.storey || 'Unknown';
    if (!byStorey[s]) byStorey[s] = [];
    byStorey[s].push(a);
  });

  var emitted = 0, clashSkipped = 0;

  Object.keys(byStorey).forEach(function(storey) {
    var storeyAnchors = byStorey[storey];
    var usedIds = {};

    steps.forEach(function(step) {
      var fromCandidates = [], toCandidates = [];
      storeyAnchors.forEach(function(a) {
        var nt = _rwToNodeType(a.anchorType, discipline);
        if (nt === step.fromNodeType) fromCandidates.push(a);
        if (nt === step.toNodeType && !usedIds[a.anchorId]) toCandidates.push(a);
      });

      if (!fromCandidates.length || !toCandidates.length) return;

      fromCandidates.forEach(function(from) {
        // Find nearest unmatched to-anchor
        var nearest = null, minDist = Infinity;
        toCandidates.forEach(function(to) {
          if (usedIds[to.anchorId]) return;
          var dx = to.x - from.x, dy = to.y - from.y;
          var dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < minDist) { minDist = dist; nearest = to; }
        });
        if (!nearest) return;

        // Sanity guard: skip distance=0 or >50m
        if (minDist === 0 || minDist > RW_MAX_PAIR_DIST) return;

        var dx = nearest.x - from.x;
        var dy = nearest.y - from.y;
        var dz = nearest.z - from.z;

        // Gradient steps: enforce slope
        if (step.offsetRule === 'GRADIENT' && step.gradient > 0) {
          var horiz = Math.sqrt(dx * dx + dy * dy);
          dz = step.gradient * horiz;
        }

        var pipeLen = Math.sqrt(dx * dx + dy * dy + dz * dz);
        var midX = (from.x + nearest.x) / 2;
        var midY = (from.y + nearest.y) / 2;
        var midZ = (from.z + nearest.z) / 2;

        // ARC envelope clash check
        if (_rwClashesWithArc(midX, midY, midZ, RW_PIPE_CROSS / 1000, RW_PIPE_CROSS / 1000, pipeLen, arcEnvelope)) {
          clashSkipped++;
          return;
        }

        // Emit pipe segment
        var info = discipline === 'CW' ? RW_IFC_MAP.PIPE_CW : RW_IFC_MAP.PIPE_SP;
        var guid = _rwGuid(discipline + '_PIPE');
        _rwInsertElement(buildingDb, guid, info.cls,
          discipline + ' Pipe ' + step.directionAxis + ' ' + storey,
          buildingName, storey, info.disc, info.rgba,
          midX, midY, midZ,
          Math.abs(dx) || RW_PIPE_CROSS / 1000,
          Math.abs(dy) || RW_PIPE_CROSS / 1000,
          Math.abs(dz) || RW_PIPE_CROSS / 1000
        );
        emitted++;
        usedIds[nearest.anchorId] = true;
      });
    });
  });

  return { emitted: emitted, clashSkipped: clashSkipped };
}

// A4. ARC envelope loader (from building DB)
function _rwLoadArcEnvelope(buildingDb) {
  var boxes = [];
  try {
    var rows = buildingDb.exec(
      "SELECT t.center_x, t.center_y, t.center_z, t.bbox_x, t.bbox_y, t.bbox_z " +
      "FROM elements_meta m JOIN element_transforms t ON m.guid = t.guid " +
      "WHERE m.discipline = 'ARC' AND m.ifc_class IN ('IfcWall','IfcWallStandardCase','IfcSlab','IfcRoof','IfcCovering')"
    );
    if (rows.length) {
      rows[0].values.forEach(function(v) {
        if (v[3] > 0 && v[4] > 0 && v[5] > 0) {
          boxes.push({ cx: v[0], cy: v[1], cz: v[2], w: v[3], d: v[4], h: v[5] });
        }
      });
    }
  } catch (e) { /* no ARC elements — no clash check */ }
  console.log('§RW_ARC_ENVELOPE boxes=' + boxes.length);
  return boxes;
}

// AABB overlap check (same as Java)
function _rwAabbOverlap(c1, s1, c2, s2, tol) {
  return Math.abs(c1 - c2) < (s1 / 2 + s2 / 2 + tol);
}

function _rwClashesWithArc(px, py, pz, pw, pd, ph, arcs) {
  for (var i = 0; i < arcs.length; i++) {
    var a = arcs[i];
    if (_rwAabbOverlap(px, pw, a.cx, a.w, RW_ARC_CLASH_TOL) &&
        _rwAabbOverlap(py, pd, a.cy, a.d, RW_ARC_CLASH_TOL) &&
        _rwAabbOverlap(pz, ph, a.cz, a.h, RW_ARC_CLASH_TOL)) {
      return true;
    }
  }
  return false;
}


// ═══════════════════════════════════════════════════════════════
// PATH B: Room-based BOM placement
// ═══════════════════════════════════════════════════════════════

/**
 * Detect rooms from building DB.
 * Uses IfcSpace elements if present, falls back to storey-level generic rooms.
 */
function _rwDetectRooms(buildingDb, buildingName) {
  var rooms = [];

  // Try IfcSpace first
  try {
    var spaceRows = buildingDb.exec(
      "SELECT m.guid, m.element_name, m.storey, " +
      "t.center_x, t.center_y, t.center_z, t.bbox_x, t.bbox_y, t.bbox_z " +
      "FROM elements_meta m JOIN element_transforms t ON m.guid = t.guid " +
      "WHERE m.ifc_class = 'IfcSpace' AND m.building = '" + buildingName.replace(/'/g, "''") + "'"
    );
    if (spaceRows.length && spaceRows[0].values.length) {
      spaceRows[0].values.forEach(function(v) {
        rooms.push({
          id: v[0], name: v[1], storey: v[2],
          type: _rwClassifyRoom(v[1], v[6] * v[7]),
          cx: v[3], cy: v[4], cz: v[5],
          bx: v[6], by: v[7], bz: v[8]
        });
      });
      console.log('§RW_ROOMS source=IfcSpace count=' + rooms.length);
      return rooms;
    }
  } catch (e) { /* no IfcSpace */ }

  // Fallback: one generic room per storey from wall envelope
  try {
    var storeyRows = buildingDb.exec(
      "SELECT m.storey, " +
      "AVG(t.center_x), AVG(t.center_y), AVG(t.center_z), " +
      "MAX(t.bbox_x), MAX(t.bbox_y), MAX(t.bbox_z), " +
      "COUNT(*) " +
      "FROM elements_meta m JOIN element_transforms t ON m.guid = t.guid " +
      "WHERE m.building = '" + buildingName.replace(/'/g, "''") + "' " +
      "AND m.discipline = 'ARC' " +
      "GROUP BY m.storey"
    );
    if (storeyRows.length) {
      storeyRows[0].values.forEach(function(v) {
        var area = (v[4] || 10) * (v[5] || 10);
        rooms.push({
          id: 'STOREY_' + (v[0] || 'Unknown'),
          name: v[0] || 'Unknown',
          storey: v[0] || 'Unknown',
          type: _rwClassifyRoom(v[0], area),
          cx: v[1], cy: v[2], cz: v[3],
          bx: v[4] || 10, by: v[5] || 10, bz: v[6] || 3
        });
      });
    }
  } catch (e) { /* empty DB */ }

  console.log('§RW_ROOMS source=storey_fallback count=' + rooms.length);
  return rooms;
}

/**
 * Classify room type from name + area, matching ad_space_type values.
 */
function _rwClassifyRoom(name, areaSqm) {
  if (!name) name = '';
  var n = name.toUpperCase();

  // Name-based classification
  if (/TOILET|BATH|WC|SHOWER|RESTROOM/.test(n)) return 'BATHROOM';
  if (/KITCHEN|PANTRY|DAPUR/.test(n)) return 'KITCHEN';
  if (/MASTER.*BED|BED.*MASTER/.test(n)) return 'MASTER_BEDROOM';
  if (/BED|BILIK\s*TIDUR/.test(n)) return 'BEDROOM';
  if (/LIVING|LOUNGE|RUANG\s*TAMU/.test(n)) return 'LIVING';
  if (/DINING|MAKAN/.test(n)) return 'DINING';
  if (/CORRIDOR|HALLWAY|LORONG/.test(n)) return 'CORRIDOR';
  if (/LOBBY/.test(n)) return 'LOBBY';
  if (/OFFICE|PEJABAT/.test(n)) return 'OFFICE';
  if (/STORE|STOR/.test(n)) return 'STORAGE';
  if (/GARAGE|PARKING/.test(n)) return 'GARAGE';
  if (/STAIR/.test(n)) return 'STAIR';
  if (/DEPART|LOUNGE/.test(n)) return 'DEPARTURE_LOUNGE';
  if (/GATE/.test(n)) return 'GATE';
  if (/CONCOURSE/.test(n)) return 'CONCOURSE';
  if (/CLASS/.test(n)) return 'CLASSROOM';
  if (/ASSEMBLY|HALL|DEWAN/.test(n)) return 'ASSEMBLY_HALL';
  if (/CANTEEN|CAFE/.test(n)) return 'CANTEEN';

  // Area-based fallback
  if (areaSqm && areaSqm < 4) return 'BATHROOM';
  if (areaSqm && areaSqm < 12) return 'BEDROOM';
  if (areaSqm && areaSqm < 25) return 'OFFICE';
  if (areaSqm && areaSqm < 50) return 'LIVING';
  return 'GENERIC';
}

/**
 * Place MEP fixtures from BOM recipes into building DB.
 * Reads ad_space_type_mep_bom + ad_placement_offset + _shim_attributes.
 */
function _rwPlaceFromBOM(buildingDb, buildingName, rooms, arcEnvelope) {
  var placed = 0;

  // Load placement offsets (keyed by rule name)
  var offsets = {};
  var offRows = _rwDb.exec("SELECT * FROM ad_placement_offset");
  if (offRows.length) {
    var cols = offRows[0].columns;
    offRows[0].values.forEach(function(v) {
      var o = {};
      cols.forEach(function(c, i) { o[c] = v[i]; });
      offsets[v[0]] = o;
    });
  }

  // Load shim attributes (keyed by product_value)
  var shims = {};
  var shimRows = _rwDb.exec("SELECT * FROM _shim_attributes");
  if (shimRows.length) {
    var scols = shimRows[0].columns;
    shimRows[0].values.forEach(function(v) {
      var s = {};
      scols.forEach(function(c, i) { s[c] = v[i]; });
      shims[v[0]] = s;
    });
  }

  rooms.forEach(function(room) {
    // Look up BOM recipe for this room type
    var bomRows = _rwDb.exec(
      "SELECT mep_product_id, qty_normal, placement_rule, host_surface, anchor_end " +
      "FROM ad_space_type_mep_bom WHERE space_type_id = '" + room.type.replace(/'/g, "''") + "'"
    );
    if (!bomRows.length) return;

    bomRows[0].values.forEach(function(v) {
      var product = v[0];
      var qty = v[1] || 1;
      var placementRule = v[2] || 'AUTO';
      var hostSurface = v[3] || 'WALL';
      var anchorEnd = v[4] || 'PANEL';

      var offset = offsets[placementRule] || offsets['AUTO'];
      if (!offset) return;

      var info = RW_IFC_MAP[product] || RW_IFC_MAP._DEFAULT;

      for (var q = 0; q < qty; q++) {
        // Compute XYZ from room bbox + placement offset
        var pos = _rwComputePosition(room, offset, hostSurface, q, qty);

        // Check ARC clash
        if (_rwClashesWithArc(pos.x, pos.y, pos.z, 0.1, 0.1, 0.1, arcEnvelope)) continue;

        var guid = _rwGuid(product);
        _rwInsertElement(buildingDb, guid, info.cls,
          product + ' ' + room.storey + (qty > 1 ? ' #' + (q + 1) : ''),
          buildingName, room.storey, info.disc, info.rgba,
          pos.x, pos.y, pos.z,
          0.15, 0.15, 0.15  // fixture bbox — small
        );
        placed++;
      }
    });
  });

  console.log('§RW_BOM_PLACE rooms=' + rooms.length + ' fixtures=' + placed);
  return { placed: placed };
}

/**
 * Compute XYZ position from room bbox + placement offset rule.
 * Implements the ad_placement_offset z_rule / x_ref / y_ref logic.
 */
function _rwComputePosition(room, offset, hostSurface, index, total) {
  var cx = room.cx, cy = room.cy, cz = room.cz;
  var hx = (room.bx || 4) / 2, hy = (room.by || 4) / 2, hz = (room.bz || 3) / 2;

  // X position
  var x = cx;
  if (offset.x_ref === 'MIN')       x = cx - hx + (offset.from_edge_x || 0);
  else if (offset.x_ref === 'MAX')  x = cx + hx - (offset.from_edge_x || 0);
  // For WALL_SPACED: distribute along wall
  if (total > 1 && hostSurface === 'WALL') {
    var wallLen = room.bx || 4;
    var spacing = wallLen / (total + 1);
    x = cx - hx + spacing * (index + 1);
  }

  // Y position
  var y = cy;
  if (offset.y_ref === 'MIN')       y = cy - hy + (offset.from_edge_y || 0);
  else if (offset.y_ref === 'MAX')  y = cy + hy - (offset.from_edge_y || 0);

  // Z position
  var z = cz;
  var zOff = offset.z_offset || 0;
  if (offset.z_rule === 'FLOOR')        z = cz - hz + zOff;
  else if (offset.z_rule === 'CEILING') z = cz + hz - zOff;
  else if (offset.z_rule === 'MID')     z = cz + zOff;

  return { x: x, y: y, z: z };
}


// ═══════════════════════════════════════════════════════════════
// PATH B (cont): Connect placed fixtures with pipe runs
// ═══════════════════════════════════════════════════════════════

/**
 * Generate pipe segments connecting placed fixtures to risers/stacks.
 * Reads the RW2D- fixtures just placed, groups by storey + anchor_end,
 * runs nearest-neighbour pairing to create pipe runs.
 */
function _rwConnectFixtures(buildingDb, buildingName, arcEnvelope) {
  var pipes = 0, clashSkipped = 0;

  // Read placed fixtures grouped by storey
  var fixRows;
  try {
    fixRows = buildingDb.exec(
      "SELECT m.guid, m.element_name, m.storey, m.discipline, " +
      "t.center_x, t.center_y, t.center_z " +
      "FROM elements_meta m JOIN element_transforms t ON m.guid = t.guid " +
      "WHERE m.guid LIKE 'RW2D-%' AND m.building = '" + buildingName.replace(/'/g, "''") + "' " +
      "AND m.ifc_class != 'IfcPipeSegment' " +
      "ORDER BY m.storey"
    );
  } catch (e) { return { pipes: 0, clashSkipped: 0 }; }
  if (!fixRows.length) return { pipes: 0, clashSkipped: 0 };

  // Group fixtures by storey
  var byStorey = {};
  fixRows[0].values.forEach(function(v) {
    var s = v[2] || 'Unknown';
    if (!byStorey[s]) byStorey[s] = [];
    byStorey[s].push({ guid: v[0], name: v[1], storey: s, disc: v[3], x: v[4], y: v[5], z: v[6] });
  });

  // For each storey, create a main run + branches
  Object.keys(byStorey).forEach(function(storey) {
    var fixes = byStorey[storey];
    if (fixes.length < 2) return;

    // Sort by X to create a main horizontal run
    fixes.sort(function(a, b) { return a.x - b.x; });

    // Connect sequential fixtures with pipe segments
    for (var i = 0; i < fixes.length - 1; i++) {
      var from = fixes[i], to = fixes[i + 1];
      var dx = to.x - from.x;
      var dy = to.y - from.y;
      var dz = to.z - from.z;
      var dist = Math.sqrt(dx * dx + dy * dy + dz * dz);

      if (dist === 0 || dist > RW_MAX_PAIR_DIST) continue;

      var midX = (from.x + to.x) / 2;
      var midY = (from.y + to.y) / 2;
      var midZ = (from.z + to.z) / 2;

      // Clash check
      if (_rwClashesWithArc(midX, midY, midZ, RW_PIPE_CROSS / 1000, RW_PIPE_CROSS / 1000, dist, arcEnvelope)) {
        clashSkipped++;
        continue;
      }

      // Determine pipe type from fixture discipline
      var pipeInfo = from.disc === 'PLB' ? RW_IFC_MAP.PIPE_SP : RW_IFC_MAP.PIPE_CW;
      var guid = _rwGuid('PIPE');
      _rwInsertElement(buildingDb, guid, pipeInfo.cls,
        'Pipe ' + storey + ' run ' + (i + 1),
        buildingName, storey, pipeInfo.disc, pipeInfo.rgba,
        midX, midY, midZ,
        Math.abs(dx) || RW_PIPE_CROSS / 1000,
        Math.abs(dy) || RW_PIPE_CROSS / 1000,
        Math.abs(dz) || RW_PIPE_CROSS / 1000
      );
      pipes++;
    }
  });

  console.log('§RW_CONNECT pipes=' + pipes + ' clashSkipped=' + clashSkipped);
  return { pipes: pipes, clashSkipped: clashSkipped };
}


// ═══════════════════════════════════════════════════════════════
// DB Write helpers
// ═══════════════════════════════════════════════════════════════

function _rwGuid(prefix) {
  _rwGuidCounter++;
  return RW_PREFIX + prefix + '-' + String(_rwGuidCounter).padStart(4, '0');
}

function _rwInsertElement(db, guid, ifcClass, name, building, storey, disc, rgba, cx, cy, cz, bx, by, bz) {
  try {
    db.run(
      "INSERT OR IGNORE INTO elements_meta (guid, ifc_class, element_name, building, storey, discipline, material_rgba) " +
      "VALUES (?, ?, ?, ?, ?, ?, ?)",
      [guid, ifcClass, name, building, storey, disc, rgba]
    );
    db.run(
      "INSERT OR IGNORE INTO element_transforms (guid, center_x, center_y, center_z, " +
      "rotation_x, rotation_y, rotation_z, bbox_x, bbox_y, bbox_z) " +
      "VALUES (?, ?, ?, ?, 0, 0, 0, ?, ?, ?)",
      [guid, cx, cy, cz, bx, by, bz]
    );
  } catch (e) {
    console.warn('§RW_INSERT_FAIL guid=' + guid + ' err=' + e.message);
  }
}


// ═══════════════════════════════════════════════════════════════
// IndexedDB cache for mep_rw.db
// ═══════════════════════════════════════════════════════════════

function _rwFetchCached(url) {
  return new Promise(function(resolve, reject) {
    var req = indexedDB.open('bim_ootb_cache', 1);
    req.onupgradeneeded = function() { req.result.createObjectStore('dbs'); };
    req.onsuccess = function() {
      var idb = req.result;
      var tx = idb.transaction('dbs', 'readonly');
      var get = tx.objectStore('dbs').get('rw_' + url);
      get.onsuccess = function() {
        if (get.result) {
          console.log('§RW_CACHE_HIT ' + url);
          resolve(get.result);
        } else {
          fetch(url).then(function(resp) {
            if (!resp.ok) throw new Error('HTTP ' + resp.status);
            return resp.arrayBuffer();
          }).then(function(buf) {
            try {
              var tx2 = idb.transaction('dbs', 'readwrite');
              tx2.objectStore('dbs').put(buf, 'rw_' + url);
            } catch (e) { /* cache write fail — continue */ }
            console.log('§RW_CACHE_WRITE ' + url + ' bytes=' + buf.byteLength);
            resolve(buf);
          }).catch(reject);
        }
      };
      get.onerror = function() {
        fetch(url).then(function(r) { return r.arrayBuffer(); }).then(resolve).catch(reject);
      };
    };
    req.onerror = function() {
      fetch(url).then(function(r) { return r.arrayBuffer(); }).then(resolve).catch(reject);
    };
  });
}
